# Generated by Django 4.1.1 on 2022-12-01 04:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ingrediants', models.TextField(max_length=150)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('process', models.TextField(max_length=450)),
                ('chef', models.CharField(max_length=40)),
                ('food_image', models.ImageField(upload_to='images')),
                ('slug', models.SlugField(unique=True)),
                ('post_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
