# Generated by Django 4.1.1 on 2022-12-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_tags_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='cooking_time',
            field=models.DurationField(default=''),
        ),
    ]
