# Generated by Django 4.1.1 on 2022-12-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_tags_cooking_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='cooking_time',
        ),
    ]
